language: java
jdk:
  - openjdk8

# 1
branches:
  only:
    - main

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2'

before_install:
  - chmod +x mvnw

# 3
script: "sudo ./mvnw clean package"

before_deploy:
  - zip -r cherrypick *
  - mkdir -p deploy
  - mv cherrypick.zip deploy/cherrypick.zip
  
 deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cherrypick-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - seoha.dev@gmail.com
