language: java
jdk:
  - openjdk8

# 1
branches:
  only:
    - main

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2'

before_install:
  - chmod +x mvnw

# 3
script: "./mvnw clean package"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/cherrypick.zip
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cherrypick-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on: 
      all_branches: true #해당 라인 추가
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cherrypick-build
    key: cherrypick.zip
    bundle_type: zip
    application: cherrypick
    deployment_group: cherrypick-group
    region: ap-northeast-2
    wait-until-deployed: true    
    on: 
      all_branches: true #해당 라인 추가
    
# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - seoha.dev@gmail.com
