language: java
jdk:
  - openjdk8

# 1
branches:
  only:
    - main

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.maven'

before_install:
  - chmod +x mvnw

# 3
script: "./mvnw clean install -DskipTests"

#step2
#before_deploy:
#  - zip -r cherrypick *
#  - mkdir -p deploy
#  - mv cherrypick.zip deploy/cherrypick.zip

#step3
before_deploy:
  # 1
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  # 2
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
#  - cp build/libs/*.jar before-deploy/
  - cp target/*.jar before-deploy/
  # 3
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/cherrypick.zip # deploy로 zip파일 이동


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cherrypick-build
    region: ap-northeast-2
    skip_cleanup: true
    wait-until-deployed: true
    acl: private
    local_dir: deploy
    on:
      all_branches: true #해당 라인 추가

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cherrypick-build
    key: cherrypick.zip
    bundle_type: zip
    application: cherrypick-webservice
    deployment_group: cherrypick-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    file_exists_behavior: overwrite
    on:
      all_branches: true #해당 라인 추가

## CI 실행 완료시 메일로 알람
## 4
#notifications:
#  email:
#    recipients:
#      - seoha.dev@gmail.com
