#default 프로필 **공통

server:
  # port: 8080 #defalut port
  servlet: 
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    path: /error
    whitelabel:
      enabled: false
          
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: seoha.mailing@gmail.com
    password: aoijcapvqagydtep
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

   # 공유디비 #나중에 nginx로 숨기기
    url: jdbc:mysql://cherrypick-db.c58cka2q8d99.ap-northeast-2.rds.amazonaws.com:3306/cherrypick?serverTimezone=Asia/Seoul
    username: seoha
    password: cpws1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  sql:
    init:
      mode: never
      
  jackson:
    serialization:
      fail-on-empty-beans: false
  
  #파일첨부
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis: 
    configuration:    
        multiple-result-sets-enabled: false    
        map-underscore-to-camel-case: true    
        call-setters-on-nulls: true        
        jdbc-type-for-null: varchar    
        default-fetch-size: 500  
    mapper-locations: com.pj.cherrypick/mapper/*.xml
    #type-aliases-package: com.pj.cherrypick.domain
