# 포트 지정
server:
  port: 80
  
# 타임리프 설정
spring: 
    thymeleaf:
        prefix : classpath:templates/
        suffix : .html
        cache : false # thymeleaf 실행시 서버에 저장을 하지 않겠다. (코드 수정 후에 서버 재실행 막기 위함.)
        
        
        
        